app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('hospitals/',views.hospitals,name="hospitals"),
    path('appointment/',views.appointment,name="appointment"),
    path('appointment2/',views.appointment2,name="appointment2"),
    path('treatment/',views.treatment,name="treatment"),
    path('contact/',views.contact,name="contact"),
    path('services/',views.services,name="services"),
    path('blog/',views.blog,name="blog"),
    path('about/',views.about,name="about"),
    path('doctors/',views.doctors,name="doctors"),
    path('confirmation/',views.confirmation,name="confirmation"),
    path('search_doctors/',views.search_doctors,name="search_doctors"),
    path('doctors_avail/<str:pk>/',views.doctors_avail,name="doctors_avail")
]

project2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.
class Hospitals(models.Model):
    h_image=models.ImageField(upload_to='hospitals')
    h_name=models.CharField(max_length=200)
    h_description=models.TextField()
    h_contact=models.CharField(max_length=13)
    h_specialities=models.IntegerField()
    h_doctors=models.IntegerField()
    viewed_on=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.h_name 

class Departments(models.Model):
    dept_name=models.CharField(max_length=100)
    dept_description=models.TextField()

    def __str__(self):
        return self.dept_name 

class Doctors(models.Model):
    doc_name=models.CharField(max_length=200)
    doc_spec=models.CharField(max_length=200)
    dept_name=models.ForeignKey(Departments,on_delete=models.CASCADE, default=1)
    doc_image=models.ImageField(upload_to='doctors')
    h_name=models.ForeignKey(Hospitals,on_delete=models.CASCADE)

    def __str__(self):
        return 'Dr.' + self.doc_name + '-('+self.doc_spec+')'

class Appointment2(models.Model):
    pf_name=models.CharField(max_length=200)
    pl_name=models.CharField(max_length=200)
    p_email=models.EmailField()
    p_contact=models.CharField(max_length=10)
    p_country=models.CharField(max_length=100)
    p_state=models.CharField(max_length=100)
    p_address=models.TextField()
    p_purpose=models.TextField()
    dept_name=models.ForeignKey(Departments,on_delete=models.CASCADE)
    doc_name=models.ForeignKey(Doctors,on_delete=models.CASCADE)
    booking_date=models.DateField()
    booked_on=models.DateTimeField(auto_now=True)

class Appointment(models.Model):
    pf_name=models.CharField(max_length=200)
    pl_name=models.CharField(max_length=200)
    p_email=models.EmailField()
    p_contact=models.CharField(max_length=10)
    p_country=models.CharField(max_length=100)
    p_state=models.CharField(max_length=100)
    p_address=models.TextField()
    p_purpose=models.TextField()
    h_name=models.ForeignKey(Hospitals,on_delete=models.CASCADE)
    dept_name=models.ForeignKey(Departments,on_delete=models.CASCADE)
    doc_name=models.ForeignKey(Doctors,on_delete=models.CASCADE)
    booking_date=models.DateField()
    booked_on=models.DateTimeField(auto_now=True)

class Home(models.Model):
    latest_update=models.CharField(max_length=220)

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from .models import Appointment2,Appointment,ContactMessage


class DateInput(forms.DateInput):
    input_type='date'

class Appointment2Form(forms.ModelForm):
    class Meta:
        model=Appointment2
        fields='__all__'

        widgets={
            'booking_date':DateInput()
        }

        labels={
            'pf_name':"First name",
            'pl_name':'Last name',
            'p_email':'Email',
            'doc_name':'Doctor Name',
           'booking_date':'Booking Date',
           'p_contact':'Contact No.',
           'p_country':'Country',
           'p_state':'state',
           'p_address':'Address',
           'p_purpose':'Purpose',
           'dept_name':'Department Name',
           'doc_name':'Doctor Name',
           'booking_date':'Appointment Date'

        }



class AppointmentForm(forms.ModelForm):
    class Meta:
        model=Appointment
        fields='__all__'

        labels={
            'pf_name':"First name",
            'pl_name':'Last name',
            'p_email':'Email',
            'doc_name':'Doctor Name',
           'booking_date':'Booking Date',
           'p_contact':'Contact No.',
           'p_country':'Country',
           'p_state':'state',
           'p_address':'Address',
           'p_purpose':'Purpose',
           'dept_name':'Department Name',
           'doc_name':'Doctor Name',
           'booking_date':'Appointment Date',
           'h_name':'Hospital Name'

        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = '__all__'

app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse 
from .models import Hospitals,Doctors,Departments,Home
from .forms import Appointment2Form,AppointmentForm,ContactForm

# Create your views here.

def home(request):
    dict_update={
        'latest_update':Home.objects.all()
    }
    return render(request,'home.html',dict_update)

def hospitals(request):
    dict_hospitals={
        'hos':Hospitals.objects.all()
    }
    return render(request,'hospitals.html',dict_hospitals)

def appointment(request):
    if request.method=='POST':
        form=AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'confirmation.html')
    form=AppointmentForm()
    dict_form={
        'app_form':form
    }
    return render(request,'appointment.html',dict_form)

def treatment(request):
    dict_dept={
        'dept':Departments.objects.all()
    }
    return render(request,'treatment.html',dict_dept)

def contact(request):
    return render(request,'contact.html')

def services(request):
    return render(request,'services.html')

def doctors(request):
    dict_doctors={
        'doc':Doctors.objects.all()
    }
    return render(request,'doctors.html',dict_doctors)

def blog(request):
    return render(request,'blog.html')

def about(request):
    return render(request,'about.html')

def confirmation(request):
    return render(request,'confirmation.html')

def search_doctors(request):
    hospitals = Hospitals.objects.all()
    departments = Departments.objects.all()
    doctors = Doctors.objects.all()

    hospital_name = request.GET.get('hospital_name')
    department_name = request.GET.get('department_name')

    if hospital_name:
        doctors = doctors.filter(h_name__h_name=hospital_name)
    if department_name:
        doctors = doctors.filter(dept_name__dept_name=department_name)

    context = {
        'doctors': doctors,
        'hospitals': hospitals,
        'departments': departments
    }

    return render(request, 'doctors.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact')  # Redirect to a success page after form submission
    form = ContactForm()
    dict_cont={'formm': form}
    return render(request, 'contact.html',dict_cont)


def appointment2(request):
    if request.method=='POST':
        form=Appointment2Form(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'confirmation.html')
    form=Appointment2Form()
    dict_form2={
        'a_form':form
    }
    return render(request,'appointment2.html',dict_form2)


def doctors_avail(request,pk):
    avail=Hospitals.objects.get(id=pk)

    return render(request,'doctors_avail.html',{"avail":avail,'form':form})

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
About Us
{% endblock %}

{% block content %}
<div class="main">
    <section class="about">
        <article>
            <h2>About HospitalBooking.com</h2>
            <p>At HospitalBooking.com, our mission is to empower healthier communities by providing seamless access to healthcare services. We understand the importance of efficient and convenient healthcare solutions, and we strive to connect patients with the best hospitals and medical professionals to meet their needs.</p>
            <img class="imgg1" src="{% static '/images//61vq+kTvDGS._AC_UF1000,1000_QL80_.jpg'%}" alt="...">
            <h3>Our Vision</h3>
            <p>Our vision is to revolutionize the way healthcare services are accessed and delivered. We envision a future where individuals can easily book appointments, access medical information, and receive quality care at their fingertips, leading to improved health outcomes and enhanced well-being for all.</p>

            <h3>Our Values</h3>
            <ul>
                <li><strong>Accessibility:</strong> We believe that everyone deserves access to quality healthcare, regardless of their location or background.</li>
                <li><strong>Transparency:</strong> We prioritize transparency in all our interactions, ensuring that patients have access to accurate information about healthcare facilities, services, and costs.</li>
                <li><strong>Innovation:</strong> We are committed to continuous innovation and improvement in the healthcare industry, leveraging technology and data-driven solutions to enhance the patient experience.</li>
            </ul>

            <h3>Our Goals</h3>
            <ul>
                <li><strong>Empowerment:</strong> Empower individuals to take control of their health and well-being by providing them with tools and resources to make informed healthcare decisions.</li>
                <li><strong>Collaboration:</strong> Foster collaboration and partnerships with healthcare providers to deliver comprehensive care to our users.</li>
                <li><strong>Impact:</strong> Make a meaningful impact on the healthcare industry and society by improving access to healthcare, reducing disparities, and promoting healthier communities worldwide.</li>
            </ul>
        </article>
    </section>


</div>
{% endblock %}

templates/appointment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Appointment
{% endblock %}

{% block content %}
<img class="appointment2-img" src="{% static '/images/doc.webp'%}" alt="">
<div class="main212">
    <div class="main1 ">

    
        <div><h1 class="app2-text">BOOK AN APPOINTMENT</h1></div>
        
        <h2 class="text-center">Make An Appointment</h2>
        
        <div class="container w-50 p-3 text-center my-5">
            <form action="" method="POST" class="form-appo2">
                {{app_form|crispy}}
                {% csrf_token %}
                <button  class="btn btn-primary mb-4">SUBMIT</button>
            </form>
        </div>
        
        </div>
</div>
{% endblock %}

templates/appointment2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Appointment
{% endblock %}

{% block content %}
<img class="appointment2-img" src="{% static '/images/doc.webp'%}" alt="">
<div class="main212">
    <div class="main1 ">

    
        <div><h1 class="app2-text">BOOK AN APPOINTMENT</h1></div>
        
        <h2 class="text-center">Make An Appointment</h2>
        
        <div class="container w-50 p-3 text-center my-5">
            <form action="" method="POST" class="form-appo2">
                {{a_form|crispy}}
                {% csrf_token %}
                <button class="btn btn-primary mb-4">SUBMIT</button>
            </form>
        </div>
        
        </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&family=Anta&family=Bebas+Neue&family=Josefin+Sans:wght@100&family=Madimi+One&family=Noto+Sans+Osmanya&family=Rubik+Mono+One&display=swap" rel="stylesheet">

    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">

    <link rel="stylesheet"
    href=" https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css ">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/scripts.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&family=Anta&family=Bebas+Neue&family=Josefin+Sans:wght@100&family=Madimi+One&family=Noto+Sans+Osmanya&family=Rubik+Mono+One&family=Staatliches&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&family=Bebas+Neue&family=Josefin+Sans:wght@100&family=Madimi+One&family=Noto+Sans+Osmanya&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&family=Bebas+Neue&family=Josefin+Sans:wght@100&family=Madimi+One&family=Noto+Sans+Osmanya&family=Rubik+Mono+One&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--GOOGLE FONTS-->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Play&display=swap" rel="stylesheet"> 

</head>
<body>
    <section id="base">
        <article>
            <div  class="title-nav1">
                <h1 class="title">HOSPITAL BOOKING.COM 
                    <span class="title-cap" style="font-size: 10px">EMPOWERING HEALTHIER COMMUNITIES</span>
                </h1>
                <div  class="title-nav">
                    <button>Register</button>
                    <button>Sign In</button>

                    <div class="dark-mode">
                        <div class="mode-toggle" onclick="toggleMode()">
                            <i class="mode-icon fas fa-toggle-on"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div>

                <ul class="nav-item">
                    <li class="home-nav nav-itemss"><a href="{% url 'home' %}"><i class="fa-solid fa-house"></i> HOME</a></li>
                    <li class="nav-itemss"><a href="{% url 'hospitals' %}"><i class="fa-solid fa-hospital"></i> HOSPITALS</a></li>
                    <li class="nav-itemss"><a href="{% url 'appointment' %}"><i class="fa-solid fa-calendar-check"></i> APPOINTMENT</a></li>
                    <li class="nav-itemss"><a href="{% url 'services' %}"><i class="fa-solid fa-handshake-angle"></i> SERVICES</a></li>
                    <li class="nav-itemss"><a href="{% url 'contact' %}"><i class="fa-solid fa-address-book"></i> CONTACT US</a></li>
                    <li class="nav-itemss"><a href="{% url 'about' %}"><i class="fa-solid fa-address-card"></i> ABOUT US</a></li>
                    <li class="nav-itemss"><a href="{% url 'blog' %}"><i class="fa-solid fa-blog"></i> BLOGS</a></li>
                    <li class="online-con"><a href="https://wa.me/1234567890?text=Hello%20World"><i class="fa-brands fa-square-whatsapp"></i>ONLINE CONSULTATION</a></li>
                </ul>
            </div>
        </article>
    </section>

    {% block content %}

    {% endblock %}


    <footer>
        <div class="footer">
        <div class="row1">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-youtube"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        </div>
        
        <div class="row">
        <ul>
        <li><a href="#">Contact us</a></li>
        <li><a href="#">Our Services</a></li>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms & Conditions</a></li>
        <li><a href="#">About Us</a></li>
        </ul>
        </div>
        
        <div class="row" style="text-align: center;padding-left:560px">
        Copyright © 2024 - All rights reserved || Designed By: Anirudh
        </div>
        </div>
        </footer>

    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
    
</body>
</html>

templates/blog.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
<div class="main">

</div>
{% endblock %}

templates/confirmation.html
{% extends 'base.html' %}

{% block title %}
Booking Confirmation
{% endblock %}

{% block content %}
<div class="main">
    <div class="container text-center">
        <h1>Booking Confirmation</h1>
        <div class="alert alert-success" role="alert">
            Your submission has be recorded
          </div>
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}
Contact Us
{% endblock %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="content">
            <div class="right-side">
                <div class="topic-text">Get in touch with us...! Send us a message</div>
                <p>Please read, understand and accept our terms of use before using this site. Any complaints or grievances regarding the use or information posted on this Site, may be sent to hospital Booking.com</p>
                <form method="POST">
                    {% csrf_token %}
                    {{ formm.as_p }}
                    <div class="button">
                        <input type="submit" class="btn btn-success" value="Send Now" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/doctors.html
{% extends 'base.html' %}

{% block title %}
Search Doctors
{% endblock %}

{% block content %}
<div style="padding: 10px;height:100%" class="main">
    <form method="GET" action="{% url 'search_doctors' %}">
        <div class="form-group">
            <label for="hospital_name">Select Hospital:</label>
            <select class="form-control" id="hospital_name" name="hospital_name">
                <option value="">-- Select Hospital --</option>
                {% for hospital in hospitals %}
                <option value="{{ hospital.h_name }}">{{ hospital.h_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="department_name">Select Department:</label>
            <select class="form-control" id="department_name" name="department_name">
                <option value="">-- Select Department --</option>
                {% for department in departments %}
                <option value="{{ department.dept_name }}">{{ department.dept_name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" style="margin-top: 10px;" class="btn btn-primary">Search</button>
    </form>

    {% if doctors %}
    <h2 style="margin-top: 20px; padding-top:12px;padding-bottom:10px;margin-right:20px;" class="bg-success">DOCTORS</h2>
    <div style="display:flex;flex-wrap: wrap; justify-content: space-around; ">
        {% for doctor in doctors %}
        <div class="card text-center mx-3 my-3 doctor-card" style="width: 18rem; display:inline-block;background-color: #faf7f7;">
            <img src="{{doctor.doc_image.url}}" class="card-img-top" style="height: 250px;width:200px; object-fit: cover;" alt="...">
            <div class="card-body">
              <h3 class="card-title">Dr.{{ doctor.doc_name }}</h3>
              <hr>
              <p class="card-text" style="font-weight: bold;">{{doctor.doc_spec}}</p>
              <h6 style="padding-bottom: 10px;"><a style="color: black; text-decoration:none;" href="">
                 <span class="department-link">{{ doctor.dept_name }} Department</span>
              </a></h6>
              <h6 class="text-success">
                <a style="color: black; text-decoration:none;" href="">
                    <span class="department-link">{{doctor.h_name}}</span>
                 </a></h6>
              <a href="{% url 'appointment' %}"><button type="button" style="margin-top:10px" class="btn btn-success">MAKE AN APPOINTMENT</button></a>
            </div>
        </div>
        {% endfor %}
    
    </div>
   
    {% else %}
    <div style="color: red;font-size:15px"><i style="font-size: 20px;padding-top:13px" class="fa-solid fa-circle-info"></i> click on Search to display options</div>
    <p>No doctors found.</p>
    {% endif %}
</div>
{% endblock %}

templates/doctors_avail.html
{% extends 'base.html' %}

{% block title %}
{{ avail.h_name }}
{% endblock %}

{% block content %}
<div class="main">
    <h1>Doctors Available at {{ avail.h_name }}</h1>
    <ul>
        {% for doctor in avail.doctors_set.all %}
            <li>{{ doctor.doc_name }} - {{ doctor.doc_spec }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/home.html

{% extends 'base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}


<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="2000">
        <img src="{% static '/images/1.jpg'%}" class="d-block w-100" alt="...">
        <h1 class="carousel-caption"><span style="color: white;font-family: Bebas Neue, sans-serif;font-weight: 400;font-style: normal;font-size:40px">"WHERE THERE IS LOVE THERE IS LIFE." </span><span style="font-size: 30px;color:white;">  - Mahatma Gandhi</span></h1>
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="{% static '/images/2.jpg'%}" class="d-block w-100" alt="...">
        <h1 class="carousel-caption">"HOSPITALITY IS NOT TO CHANGE PEOPLE, BUT TO OFFER THEM SPACE WHERE CHANGE CAN TAKE PLACE."  <span style="font-size: 30px;">  - Henri Nouwen</span></h1>
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/3.jpg'%}" class="d-block w-100" alt="...">
        <h2 class="carousel-caption"><span style="color: white;font-family: Bebas Neue, sans-serif;font-weight: 400;font-style: normal;font-size:40px">"HEALTH IS THE CROWN ON THE WELL PERSON'S HEAD THAT ONLY THE ILL PERSON CAN SEE."</span><span style="font-size: 30px;color:white"> - Robin Sharma</span></h2>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="noti">
    <div><h4>LATEST UPDATES</h4></div>
    <div class="scrolling-text">
        {% for update in latest_update %}
            {{ update.latest_update }}
        {% endfor %}
    </div>
  </div>
  <div class="youtube1">
    <iframe width="830px" height="500px" src="https://www.youtube.com/embed/RtYwGTMPe1E?si=XetZFqTfsZESGnZI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <div class="insure">
        <h3>HEALTH INSURANCE (COVID-19 Covered)*</h3>
        <p><span style="color:rgb(184, 185, 184);padding-bottom:35px;">Start Your Health Insurance Journey Today!</span><br><br>
            Health insurance policy is a product that protects you against the financial implications of a wide variety of health-related expenses, ranging from those caused by minor illnesses and injuries to critical diseases. Therefore, health insurance plans and the cumulative Bonus serve as a protective financial shield for you should you be faced with a major medical expense.
            
            Selecting a suitable medical insurance is difficult yet incredibly important for you to have a sufficient degree of preparedness against any sudden and, in some cases, expected medical expenses. Imagine a scenario wherein you are diagnosed with a serious medical condition that requires consistent treatment, hospitalisation, and/or surgery. Or simply take the example of the spread of COVID-19 in India and imagine the various expenses you may have to look after if diagnosed with a COVID-19 infection
            
            In such a situation, you would not want to let your medical bills dig a massive hole in your savings or be faced with a financial crisis to pay said bills, will you? Hence it is pivotal to buy a suitable health insurance plan, choose the right sum insured, pay the applicable premium and get insured at the earliest, and we can help you with that.</p>
    </div>
  </div>

  <div class="image-flow">
    <img class="imgg1" src="{% static '/images/20596093.jpg'%}" alt="...">
    <img class="imgg2" src="{% static '/images/Q8Ukgz.webp'%}" alt="...">
    <h1>THE HEARTBEAT OF COMMUNITY WELLNESS</h1>
  </div>

{% endblock %}

templates/hospitals.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Hospitals
{% endblock %}

{% block content %}
<style>
.card {
    max-height: 550px; /* Adjust the maximum height as needed */
}
</style>

<div style="display: flex;flex-wrap: wrap; justify-content: space-around; padding: 10px;height:100%" class="main d-flex flex-wrap">
    {% for i in hos %}
    <div class="card m-2" style="width: 18rem;">
        <img class="card-img-top" src="" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{i.h_name}}</h5>
          <p class="card-text">{{i.h_description}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{i.h_contact}}</li>
          <a href="{% url 'treatment' %}"><li class="list-group-item">Specialities <span style="font-weight: bold;">{{i.h_specialities}}</span></li></a>
          <a href="{% url 'doctors_avail' pk=i.pk %}"><li class="list-group-item">Doctors <span style="font-weight: bold;">{{i.h_doctors}}</span></li></a>
        </ul>
        <div class="card-body">
          <a href="{% url 'appointment2' %}"><button style="margin-left: 35px;" type="button" class="btn btn-primary ">BOOK APPOINTMENT</button></a>
        </div>
      </div>
      {% endfor %}
</div>
{% endblock %}

templates/treatment.html
{% extends 'base.html' %}

{% block title %}
dept
{% endblock %}

{% block content %}
<h1 class="text-center" style="padding-top: 40px;"> Departments</h1>
<hr>
<div class="main">
    <div class="card" style="margin-left:20px;margin-right:20px;">
        <h5 class="card-header">Current Departments</h5>
        {% for i in dept %}
        <div class="card-body cardno" style="background-color: rgb(200, 201, 201);" >
          <h4 class="card-title  pb-1" style="font-weight: 500;">{{i.dept_name}}</h4>
          <p class="card-text">{{i.dept_description}}</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
        <div style="background-color: white;height:10px"></div>
        {% endfor %}
      </div>
</div>


{% endblock %}